# Auto-generated using compose2nix v0.3.2-pre.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  secrets = builtins.exec [
    "bash"
    "-c"
    "age --decrypt -i /home/rok/.ssh/id_ed25519 ./secrets/archive-0.age"
  ];
in
{
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."qbittorrent-qbittorrent-nox" = {
    image = "qbittorrentofficial/qbittorrent-nox";
    environment = {
      "QBT_CONFIG_PATH" = "/config/qBittorrent/";
    };
    volumes = [
      "/mnt:/mnt:rw"
      "qbittorrent_tailscale-qbittorrent-nox:/config/qBittorrent:rw"
    ];
    dependsOn = [
      "qbittorrent-tailscale"
    ];
    ports = [
      "8081:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:qbittorrent-tailscale"
    ];
  };
  systemd.services."podman-qbittorrent-qbittorrent-nox" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-volume-qbittorrent_tailscale-qbittorrent-nox.service"
    ];
    requires = [
      "podman-volume-qbittorrent_tailscale-qbittorrent-nox.service"
    ];
    partOf = [
      "podman-compose-qbittorrent-root.target"
    ];
    wantedBy = [
      "podman-compose-qbittorrent-root.target"
    ];
  };
  virtualisation.oci-containers.containers."qbittorrent-tailscale" = {
    image = "tailscale/tailscale:latest";
    environment = {
      "TS_AUTHKEY" = secrets.TS_AUTHKEY;
      "TS_EXTRA_ARGS" = "--exit-node=100.115.43.17 --accept-routes=true";
      "TS_STATE_DIR" = "/var/lib/tailscale";
      "TS_USERSPACE" = "false";
      "TS_TAILSCALED_EXTRA_ARGS" = "--tun=userspace-networking";
    };
    volumes = [
      "/dev/net/tun:/dev/net/tun:rw"
      "qbittorrent_tailscale-qbittorrent-nox:/var/lib/tailscale:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      # "--privileged"
      # "--net=host"
      "--cap-add=NET_ADMIN"
      "--cap-add=NET_RAW"
      "--cap-add=sys_module"
      "--hostname=tailscale-qbittorrent-nox"
      "--network-alias=tailscale"
      "--network=qbittorrent_default"
    ];
  };
  systemd.services."podman-qbittorrent-tailscale" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-qbittorrent_default.service"
      "podman-volume-qbittorrent_tailscale-qbittorrent-nox.service"
    ];
    requires = [
      "podman-network-qbittorrent_default.service"
      "podman-volume-qbittorrent_tailscale-qbittorrent-nox.service"
    ];
    partOf = [
      "podman-compose-qbittorrent-root.target"
    ];
    wantedBy = [
      "podman-compose-qbittorrent-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-qbittorrent_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f qbittorrent_default";
    };
    script = ''
      podman network inspect qbittorrent_default || podman network create qbittorrent_default
    '';
    partOf = [ "podman-compose-qbittorrent-root.target" ];
    wantedBy = [ "podman-compose-qbittorrent-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-qbittorrent_tailscale-qbittorrent-nox" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect qbittorrent_tailscale-qbittorrent-nox || podman volume create qbittorrent_tailscale-qbittorrent-nox
    '';
    partOf = [ "podman-compose-qbittorrent-root.target" ];
    wantedBy = [ "podman-compose-qbittorrent-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-qbittorrent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
