# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.config.rocmSupport = false;

  # hardware.opengl = {
  #   enable = true;
  #   # driSupport = true;
  #   # driSupport32Bit = true;
  # };

  # sound.enable = true;
  hardware.firmware = [ pkgs.rtl8761b-firmware ];
  # hardware.pulseaudio.enable = false;
  # hardware.pulseaudio.enable = lib.mkForce false;
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true;

  # hardware.amdgpu.opencl.enable = true;
  # hardware.bluetooth.settings = {
  #   General = {
  #     Experimental = true;
  #     Enable = "Source,Sink,Media,Socket";
  #   };
  # };

  # TODO after 24.11
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      rocmPackages.clr.icd # OpenCL
      libva # VA-API
    ];
  };

  environment.systemPackages = with pkgs; [
    rocmPackages.rocm-smi
    rocmPackages.rocminfo
  ];

  # create a linked path for rocm libraries that might be hardcoded in
  # various libraries and packages
  systemd.tmpfiles.rules =
    let
      rocmEnv = pkgs.symlinkJoin {
        name = "opt-rocm";
        paths = with pkgs.rocmPackages; [
          rocblas
          hipblas
          clr
        ];
      };
    in
    [
      "L+    /opt/rocm   -    -    -     -    ${rocmEnv}"
    ];

  hardware.amdgpu = {
    # load the amdgpu driver earlier
    initrd.enable = true;
    # enable Sea Islands (CIK i.e. GCN 2) cards support in amdgpu driver
    # for the AMD Oland PRO [Radeon R7 240/340 / Radeon 520] old card
    legacySupport.enable = true;

    # rocm clr drivers
    opencl.enable = true;

    # additional Vulkan drivers for AMD
    # amdvlk.enable = true;
  };

  # replace with pipewire
  # hardware.pulseaudio.extraConfig = ''
  #   load-module module-switch-on-connect
  # '';

  # hardware.pulseaudio.configFile = pkgs.writeText "default.pa" ''
  #   unload-module module-suspend-on-idle
  #   # load-module module-bluetooth-policy
  #   # load-module module-bluetooth-discover
  # '';

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  # boot.initrd.kernelModules = [];
  boot.initrd.kernelModules = [
    "virtio_balloon"
    "virtio_console"
    "virtio_rng"
    "virtio_gpu"
    "amdgpu"
  ];
  boot.kernelModules = [
    "kvm-amd"
    "amdgpu"
  ];
  boot.extraModulePackages = [ ];
  boot.extraModprobeConfig = "options kvm_amd nested=1"; # nested virtualization https://nixos.wiki/wiki/Libvirt

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0e99e297-18b6-4f06-b4be-4aa907e27371";
    fsType = "ext4";
  };

  fileSystems."/mnt/home.local/cache" = {
    device = "/dev/disk/by-uuid/7676e2aa-8290-4023-b70e-faf566f4381d";
    fsType = "ext4";
  };
  system.activationScripts.fix-perm.text = ''
    chmod 777 /mnt/home.local/cache
  '';

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BD68-9292";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
