# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "virtio_pci" "usbhid" "usb_storage" "sr_mod"];
  boot.binfmt.emulatedSystems = ["x86_64-linux"];

  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8238b793-ea06-49bd-b591-fb3b91da2cfa";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/302C-183D";
    fsType = "vfat";
  };
  
  # It's too slow.
  # fileSystems."/mnt/macos_ro" = {
  #   device = "share";
  #   fsType = "9p";
  #   options = ["trans=virtio" "version=9p2000.L" "rw" "_netdev" "nofail" "noatime"];
  #   noCheck = true;
  # };
  #
  # fileSystems."/home/rok/mac" = {
  #   device = "/mnt/macos_ro";
  #   fsType = "fuse.bindfs";
  #   options = ["map=1095052480/1000:@390463540/@100" "x-systemd.requires=/mnt/macos_ro" "_netdev" "auto" "nofail" "noatime"];
  #   noCheck = true;
  # };

  swapDevices = [];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
