# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      # ./lxd.nix
      # Include the OrbStack-specific configuration.
      # ./orbstack.nix
    ];

  users.users."kyungrok.chung" = {
    uid = 1095052480;
    extraGroups = [ "wheel" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/kyungrok.chung";
    homeMode = "700";
    useDefaultShell = true;
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Asia/Seoul";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      -----BEGIN CERTIFICATE-----
MIIDvTCCAqWgAwIBAgIFAO79hJcwDQYJKoZIhvcNAQELBQAwPTE7MDkGA1UEAxMy
VG9zcyBTZWN1cml0aWVzIEpTUyBCdWlsdC1pbiBDZXJ0aWZpY2F0ZSBBdXRob3Jp
dHkwHhcNMjIwMzA3MDE0ODU3WhcNMzIwMzA4MDE0ODU3WjA9MTswOQYDVQQDEzJU
b3NzIFNlY3VyaXRpZXMgSlNTIEJ1aWx0LWluIENlcnRpZmljYXRlIEF1dGhvcml0
eTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANIJFE3V0y3U7gnSxxJb
m0+AuXAISZmH+6vOXobwWa07e88neIMhcTCRszzDEBGR8OI/9RHYxP0AsvUx9D+l
YNrN8WsJiRayjsgB22OJWCLp0J8tt4JRmWkQjV2KNFm2L0LhCS3A1pXXiKO2m2GE
snBban3hlVCI+Lx+oYiXb0tWaK9qC90+q3y76Fa1RMaklcOOufobYrELJxhW/AyK
0MLbxZxt+3dEdGTxzTmAgNNKQlOhizopfW4U/072irexgbCNO6QroBUdHuQI8+1y
1PFAiyKNZkLwrjcBO6BnL+knaGaZrYjVg9jLhK7C1h0yWj7eCBq3jAs3JJ5scTjk
47UCAwEAAaOBwzCBwDAdBgNVHQ4EFgQUttNUDoPnzHNvC1hKXQOkG26uljUwEwYD
VR0lBAwwCgYIKwYBBQUHAwEwDgYDVR0PAQH/BAQDAgGmMA8GA1UdEwEB/wQFMAMB
Af8wSAYDVR0fBEEwPzA9oDugOYY3aHR0cHM6Ly90b3Nzc2VjdXJpdGllcy5qYW1m
Y2xvdWQuY29tLy9DQS9KQU1GQ1JMU2VydmxldDAfBgNVHSMEGDAWgBS201QOg+fM
c28LWEpdA6Qbbq6WNTANBgkqhkiG9w0BAQsFAAOCAQEA0Bs2wgvranqBEgP16E9U
AY1km2QQzOyQOOQFsite+62gV5QbjcFAuSrFuAZ/tUWiZiP4Siy+ZRwHzajzNx3/
1xJ8UwKBcB5V0dwae0cbipa6ZY57eWZC/RlssLpUnyWGhTLrre+0eyOkVkmolKdJ
ctmV2UVHmnAnYyBbGYHh1DnazLTHBgVJ09W6Ld5XEV91eacGbKhGrTAEXqnXEv65
aqZU8xnyyFaTlcN17GYaZS1G/6m/Jjjs1JmMcb6+48I0pOSv8zWWG4380IfQ9o0S
6Qf+7qOPb4pOABvxwrgzUjBVVysoz5Z3dXMZrR6MlKgqzn7Gp9hNt2KKr92hzyxc
UQ==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEDTCCAvWgAwIBAgICATgwDQYJKoZIhvcNAQELBQAwgZ4xJTAjBgkqhkiG9w0B
CQEMFmNlcnRhZG1pbkBuZXRza29wZS5jb20xGzAZBgNVBAMMEiouc2luMi5nb3Nr
b3BlLmNvbTESMBAGA1UECwwJY2VydGFkbWluMRYwFAYDVQQKDA1OZXRza29wZSBJ
bmMuMRIwEAYDVQQHDAlTaW5nYXBvcmUxCzAJBgNVBAgMAlNHMQswCQYDVQQGDAJT
RzAeFw0yMjA4MjYxMTExMjhaFw0zMjA4MjMxMTExMjhaMIGeMSUwIwYJKoZIhvcN
AQkBDBZjZXJ0YWRtaW5AbmV0c2tvcGUuY29tMRswGQYDVQQDDBIqLnNpbjIuZ29z
a29wZS5jb20xEjAQBgNVBAsMCWNlcnRhZG1pbjEWMBQGA1UECgwNTmV0c2tvcGUg
SW5jLjESMBAGA1UEBwwJU2luZ2Fwb3JlMQswCQYDVQQIDAJTRzELMAkGA1UEBgwC
U0cwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCoHoeq8Je8uOUlNhLy
sXSzZouTR4CERbydCJPr3BIz9POnWG+Ee67dAgUYaIKVPSqYVqY8LLs6g45tAELm
oVgMnX8FbrHD29PuYYm0yqIM76eRFgIJbFjN+5ycoustHaa2J9ModL+csTyt33Y/
5Uzdad7/YHwnVhxa2fYLmrGvxaYJJ6j4WH9k0TCZufLAyY69PWPqgI4H9gfLgBV1
pbNS3YFqZvww+3mZIrttwoyXTwTFtWMtiwOrZ2Ila90/6zZ5GBeR0syLQ63sG0TK
9AbmhZ0dAX3Wk8/fFluqxZS6uxlETHLXZ4o8Bp9SSEXXXPKrRBW82JWmXTEDw2LV
N0KtAgMBAAGjUzBRMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKHpWcD/voOM
AAy5jQJyB0Jg0DAYMB8GA1UdIwQYMBaAFKHpWcD/voOMAAy5jQJyB0Jg0DAYMA0G
CSqGSIb3DQEBCwUAA4IBAQCBZ3yhZyDLeKM3sBctx3k4ddwab0GFWo2vrd1Ds5A2
tWWGOo7f7MwISXYO701ruyjIP8ZiEY+lc8I9de3FYLGUzYGCUn7QWuOD/RjKTsOg
kj1LhMoPWg8hs81MPY6mK1FC19euidtwZAHXV4BLkECx5pJG1cqyVf5AIu1XlgDm
9NYAP1MZDFVsvnF6EVGcbWMl2zxkTXRgJhmCWAnsPT520Uvvnff813YzfafDGzT4
Fz3FwfJAc/+IfY+RQiVezKsk8WRRI1AEQmsRWDl6YA/pGeGvtFDQZ8dx1TACxWhW
zSCSMuE3eKl2CWZJfwJBb5Vly5ULnRqXaB/lkAHvwvgA
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIID1jCCAr6gAwIBAgIUBz8Qc55zauB6TgBFqEUhbc4OEHMwDQYJKoZIhvcNAQEL
BQAwgZoxCzAJBgNVBAYTAktSMQ4wDAYDVQQIDAVTZW91bDEOMAwGA1UEBwwFU2Vv
dWwxEzARBgNVBAoMCnRvc3NpbnZlc3QxETAPBgNVBAsMCFNlY3VyaXR5MRswGQYD
VQQDDBJ0b3NzaW52ZXN0X2JsdWVtYXgxJjAkBgkqhkiG9w0BCQEWF3NlY3VyaXR5
QHRvc3NpbnZlc3QuY29tMCAXDTIxMDMwOTAzNTIzN1oYDzIwNTEwMzAyMDM1MjM3
WjCBmjELMAkGA1UEBhMCS1IxDjAMBgNVBAgMBVNlb3VsMQ4wDAYDVQQHDAVTZW91
bDETMBEGA1UECgwKdG9zc2ludmVzdDERMA8GA1UECwwIU2VjdXJpdHkxGzAZBgNV
BAMMEnRvc3NpbnZlc3RfYmx1ZW1heDEmMCQGCSqGSIb3DQEJARYXc2VjdXJpdHlA
dG9zc2ludmVzdC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDe
BGM+RHU9Iq3mOdiihknjSAZFkgVlGicbRmFWjXn3r7+RtqKXva/p0nekrp6NowqF
o49KQkfmENd78ivnL/n8r1hRs18oceZpvRtb333bczdEJw+6QyDmrfjBa5uKq/75
oWlElcrDMO3XmdeqrXOcXE0/IRVgmZD0s7c/zfmK8Ccw8p0uvMsHk141OEpKWKs0
YJFly1zyVj1FWk5Q88by4IiezQqDQTfGMuJlh24BmmqRvPvv6ZinoYTpiyVnR/BC
S/Fcesy3yu2kcrQxJv2tu06a7tbS9lJlzIM9V2LZAy4Wuek+da2lqwzEiyJGirFW
UBFqQigPUrEmF2lAvLZZAgMBAAGjEDAOMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcN
AQELBQADggEBAENcFBHEYvVGRGG/V4Yg0toPY/qqQKNEW2PcntcpP9wUB5zpAwB2
yJyTHXTZAqKWTRRFSw54AgVfbaH+k+AZDrj7WxvhuBh5Y9Twa928S2kAyioRcu3v
hLgkYmqFUMInjGc0NN/SzPS7HPZl2d1jASab0CVItUcb5A0WM/86plmiPhGMxE8/
20Sxn3ObGxdo2F1413270/Ms6v3ZYy01qnzXp89Jgjpnl0Ay9K+Tk98ODc62aFaj
xGHWC2AxxUmuZbhljmwqLGRzTiEI6uHtqdS4tSfZAHSLzgn8kq62hwKAlEOLU+O7
38+lgrBJTAFJaYBtzWIc3sBvuGlpCMQAKgc=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIDpTCCAo2gAwIBAgIQAIH6gN6qm7NsK9Ba1UpG2DANBgkqhkiG9w0BAQsFADBf
MRIwEAYDVQQDDAllRXllRW1zQ0ExJjAkBgkqhkiG9w0BCQEWF3N1cHBvcnRAYmV5
b25kdHJ1c3QuY29tMRQwEgYDVQQKDAtCZXlvbmRUcnVzdDELMAkGA1UEBhMCVVMw
HhcNMjQwMjI3MDYxNjUxWhcNMzQwMjI4MDYxNjUxWjBfMRIwEAYDVQQDDAllRXll
RW1zQ0ExJjAkBgkqhkiG9w0BCQEWF3N1cHBvcnRAYmV5b25kdHJ1c3QuY29tMRQw
EgYDVQQKDAtCZXlvbmRUcnVzdDELMAkGA1UEBhMCVVMwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQCLMjIeQS/30fp1Z6eAPv83uhNSQqao/Mfm+qayn/c6
wfIfNrmMoXH67p3iN4scKMOGsnciUN5jWPLOFIlWHeR7jHKj22zam/qR7ex5Azvj
BYfouCivVhQ5vzdtgfqHNyRqHu7zuRIJxDKKTI6GNAvakj66J8r8tzwtxLiKRh/P
LoZllzJc+92xYLk1mDbXLxKdz8W95DCJ2EY2nqi4sO0msuzwJY2lH31uljvYPUmG
prOAWzpYeB8DF0js56P6zO1+lcGYoweDCK2tsCZ3kOTfKA7buCmTPNvCgchZNgOv
tEetpWYbSO2VOGbu2j47BLkghyzSqYoe3wUXZjbT1LaNAgMBAAGjXTBbMB0GA1Ud
DgQWBBS+VcovB4vTkT+0msnXJ3n9pzgezjALBgNVHQ8EBAMCAcYwDAYDVR0TBAUw
AwEB/zAfBgNVHSMEGDAWgBS+VcovB4vTkT+0msnXJ3n9pzgezjANBgkqhkiG9w0B
AQsFAAOCAQEAOh8vSOLePcID+qn9fPFQuGUt6NZhn2mJwRoFfK2f2rFUWMb0yUkW
xjvKjDLq+YLN09NDKcuFwpTGovXWwBUGIaiL+2ZLio5ArgWTYeY9LblcQ2nqvPlF
9jpIluWX4QI1OJD9WNRNCIuL2kyK/qvUtbDcJYZp40z1nIOKB/r6csExAedAy8dQ
36d4fAdpuX4aecc9DmpG6c2WGlcaYs2LgLQj91XYGspRuGpOwnRXayCY29W3nK0e
5AK1zNPsF+GI93wtrlxEpKI3PlwwVqasCmCeZZ+dX+KeMHo2LoSLzRAqsbtksyGI
6JA9HFswo+DX+SxT6WexYhs693MJPqI6og==
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIID6jCCAtKgAwIBAgIIFCzbtDx3Zf8wDQYJKoZIhvcNAQELBQAwejELMAkGA1UE
BhMCSUUxDTALBgNVBAcMBENvcmsxFzAVBgNVBAoMDkZvcmNlcG9pbnQgTExDMR8w
HQYDVQQLDBZGb3JjZXBvaW50IEVuZ2luZWVyaW5nMSIwIAYDVQQDDBlGb3JjZXBv
aW50IEYxRSBOUCBSb290IENBMB4XDTI0MTExMjA4MzUxMFoXDTI3MDIxNDA4MzUx
MFowejELMAkGA1UEBhMCSUUxDTALBgNVBAcMBENvcmsxFzAVBgNVBAoMDkZvcmNl
cG9pbnQgTExDMR8wHQYDVQQLDBZGb3JjZXBvaW50IEVuZ2luZWVyaW5nMSIwIAYD
VQQDDBlGb3JjZXBvaW50IEYxRSBOUCBSb290IENBMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAtPrg4Ed47+nhZf+27sffkzuEZHIc3TMhK0stN1MpuVQ+
RGyZgHD19AHPNqdn3UYphER8/J6JWTlDQzwNVMHYLZLDj7Phafysethv9wQxTqV/
fypsSTPYVn2/56K5s1AhT7xmTZdyw829qq6WvXJaGpqZJfabgyBHzd6JAOIUjEBB
1Oy16/ANhx8+tKpEB6BaqGt17io3QDEwhfB7YLyxvRLtANsKx4h4mzorn93jUX86
BQ9SiqFzSHsMARC/PQ3A3yWK0tO/3MOgOcOp5l2qp9ycIJgp9v2YMuBb8Tl5aGVN
AmcmWjETllggtFkkGIzdaQvQ4by57zx+PrlRRQgbgQIDAQABo3QwcjAPBgNVHRMB
Af8EBTADAQH/MA4GA1UdDwEB/wQEAwICBDAdBgNVHQ4EFgQUYtpOlRPyWr8xBvNy
VqQkiKE6auEwHwYDVR0jBBgwFoAUYtpOlRPyWr8xBvNyVqQkiKE6auEwDwYKKwYB
BAGC8008AQQBMTANBgkqhkiG9w0BAQsFAAOCAQEAQ3Pp76c1teSjPrwRZAS5F1v4
jOHUph1kFgTgpovUGoy5HAMvbym9Oe3oybkDhw7i0uE641QpNUawrvvA4v9fZN1M
h3mc0jtzl66pKnNf90afJupJTvG6aBri9W8RvtoIIo95ucn3aUlxi/TecpnrAjTl
pNUAtSAI88ZDJj4hLLh0sT+gNOzNHTApilhAgrB+OcAFQwfofoRBKNv47Ikihoy3
h5thbvsXZqC6+9hNkN1uzj+T+l5l7QQe+0MVKq/wDF5bi5hN5+5A/ht1LAvgbagr
cSkpjP40nriYryWZiIobxwpD4xj6gwmd48sy3Aar/qM4Lu7XHuPOW6TQjDW6qw==
-----END CERTIFICATE-----

    ''
  ];

 networking.hostName = "txxx-nix"; 

  # Add OrbStack CLI tools to PATH
  environment.shellInit = ''
    . /opt/orbstack-guest/etc/profile-early

    # add your customizations here

    . /opt/orbstack-guest/etc/profile-late
  '';

  # Enable documentation
  documentation.man.enable = true;
  documentation.doc.enable = true;
  documentation.info.enable = true;

  # Disable systemd-resolved
  services.resolved.enable = false;
  environment.etc."resolv.conf".source = "/opt/orbstack-guest/etc/resolv.conf";

  # Faster DHCP - OrbStack uses SLAAC exclusively
  networking.dhcpcd.extraConfig = ''
    noarp
    noipv6
  '';

  # Disable sshd
  services.openssh.enable = lib.mkForce false;

  # systemd
  systemd.services."systemd-oomd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-userdbd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-udevd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timesyncd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-timedated".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-portabled".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-nspawn@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-machined".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-localed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-logind".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald@".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journald".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-remote".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-journal-upload".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-importd".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-hostnamed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-homed".serviceConfig.WatchdogSec = 0;
  systemd.services."systemd-networkd".serviceConfig.WatchdogSec = lib.mkIf config.systemd.network.enable 0;

  # ssh config
  programs.ssh.extraConfig = ''
    Include /opt/orbstack-guest/etc/ssh_config
  '';

  # indicate builder support for emulated architectures
  nix.settings.extra-platforms = [
    "x86_64-linux"
    "i686-linux"
  ];

  # This option defines the first version of NixOS you have installed on this particular machine,
  # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
  #
  # Most users should NEVER change this value after the initial install, for any reason,
  # even if you've upgraded your system to a new NixOS release.
  #
  # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
  # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
  # to actually do that.
  #
  # This value being lower than the current NixOS release does NOT mean your system is
  # out of date, out of support, or vulnerable.
  #
  # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
  # and migrated your data accordingly.
  #
  # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
  system.stateVersion = "24.05"; # Did you read the comment?

}
