#!/usr/bin/env bash
set -euxo pipefail
# hostname=$(hostname -s)
# case "$(hostname -s)" in
#   *chung02)
#     hostname=txxx
#     ;;
# esac
#
# export NIXPKGS_ALLOW_INSECURE=1
# export GIT_SSH_COMMAND='ssh -J rok@root -i /home/rok/.ssh/id_ed25519'

sudo NIXPKGS_ALLOW_UNFREE=1 nixos-rebuild dry-build --flake .#home --impure
