#!/usr/bin/env bash
set -euxo pipefail
hostname=$(hostname -s)
case "$(hostname -s)" in
  *chung02)
    hostname=rok-toss
    ;;
esac

export NIXPKGS_ALLOW_INSECURE=1

# nix flake update
if OS_NAME=$(uname -s) && [ "$OS_NAME" = "Darwin" ]; then
  nix run nix-darwin -- switch --flake ".#${hostname}" --impure "$@"
else
  sudo NIXPKGS_ALLOW_INSECURE=1 nixos-rebuild switch --flake ".#${hostname}" --impure "$@"
fi
