#!/usr/bin/env bash
set -euxo pipefail
hostname=$(hostname -s)
case "$(hostname -s)" in
  *chung02)
    hostname=rok-txxx
    ;;
esac

export NIXPKGS_ALLOW_INSECURE=1
export GIT_SSH_COMMAND='ssh -J rok@root -i /home/rok/.ssh/id_ed25519'


# nix flake update
if OS_NAME=$(uname -s) && [ "$OS_NAME" = "Darwin" ]; then
  nix run nix-darwin -- switch --flake ".#${hostname}" --impure "$@"
else
  NIXPKGS_ALLOW_INSECURE=1 sudo nixos-rebuild switch --flake ".#${hostname}" --impure  "$@" 
  # sudo GIT_SSH_COMMAND='ssh -J rok@root -i /home/rok/.ssh/id_ed25519' nixos-rebuild switch --flake ".#${hostname}" --impure "$@"
fi
