#!/usr/bin/env bash
set -euxo pipefail

# touch /home/rok/.config/sway/.swayswitch
# ls /home/rok/.config/sway/.swayswitch || echo 0 > /home/rok/.config/sway/.swayswitch

if [[ $(swaymsg -t get_outputs | jq '.[] | select(.model == "LG TV SSCR2") | .active') == "false" ]]; then
    swaymsg output '"LG Electronics LG HDR 4K 104NTLE5N480"' enable mode 3840x2160 pos 1920 0 scale 2 transform 0
    swaymsg output '"LG Electronics LG TV SSCR2 0x01010101"' enable mode 3840x2160 position 0 0 scale 2 transform 0
    swaymsg output '"Dell Inc. DELL P2421D 9XJVQ33"' disable
else
    swaymsg output '"Dell Inc. DELL P2421D 9XJVQ33"' enable mode 2560x1440 pos 0 0 scale 1 transform 180
    swaymsg output '"LG Electronics LG HDR 4K 104NTLE5N480"' disable
    swaymsg output '"LG Electronics LG TV SSCR2 0x01010101"' disable
fi
