#!/usr/bin/env bash
set -euxo pipefail
touch ~/.config/sway/.swayswitch
ls ~/.config/sway/.swayswitch || echo 0 > ~/.config/sway/.swayswitch

if [[ $(cat ~/.config/sway/.swayswitch) -eq 0 ]]; then
    # 1
    echo 1
    swaymsg output '"LG Electronics LG HDR 4K 104NTLE5N480"' enable mode 3840x2160 pos 3840 0 scale 2 transform 0
    swaymsg output '"LG Electronics LG TV SSCR2 0x01010101"' enable mode 3840x2160 position 0 0 scale 2 transform 0
    swaymsg output '"Dell Inc. DELL P2421D 9XJVQ33"' disable
    echo 1 > ~/.config/sway/.swayswitch
else
    swaymsg output '"LG Electronics LG HDR 4K 104NTLE5N480"' disable
    swaymsg output '"LG Electronics LG TV SSCR2 0x01010101"' disable
    swaymsg output '"Dell Inc. DELL P2421D 9XJVQ33"' enable mode 2560x1440 pos 0 0 scale 1 transform 180
    echo 0
    echo 0 > ~/.config/sway/.swayswitch
fi
