#!/usr/bin/env bash
set -euxo pipefail

touch ~/.config/sway/.swayswitch

ls ~/.config/sway/.swayswitch || echo 0 > ~/.config/sway/.swayswitch

# swaymsg -t get_outputs | jq -r '.[] | (.name) + "\t" + (.model)' | fzf | awk '{print $1}'
# HDMI-A-1: main
# DP-1: side
# DP-2: bed

if [[ $(cat ~/.config/sway/.swayswitch) -eq 0 ]]; then
    swaymsg output HDMI-A-1 enable mode 3840x2160 position 0 0 scale 2 transform 0
    swaymsg output DP-1 enable mode 1920x1080 pos 3840 0 scale 1.5 transform 0
    swaymsg output DP-2 disable
    echo 1 > ~/.config/sway/.swayswitch
else
    swaymsg output HDMI-A-1 disable
    swaymsg output DP-1 disable
    swaymsg output DP-2 enable mode 2560x1440 position 0 0 scale 1.5 transform 180
    
    # swaymsg output HDMI-A-1 enable mode 3840x2160 position 0,0 scale 2 transform 0
    # swaymsg output DP-1 enable mode 1920x1080 pos 0 0 scale 1.5 transform 0
    # swaymsg output DP-2 mode 1920x1080 pos 1920 0 scale 1.5 transform 180 enable
    echo 0 > ~/.config/sway/.swayswitch
fi
